#:kivy 1.0

## Set <key> <expr>
#:set conn_green (0, 1, .5, .8)
#:set conn_yellow (1, 1, 0, .8)
#:set conn_red (1, 0, 0, .8)


# Root widget description
<LTC>:
    indicators: indicators
    toplayout: toplayout

    BoxLayout:
        size: root.size
        orientation: 'vertical'
        padding: 5
        spacing: 10

        # Parent widget of the State display and Relay controls
        BoxLayout:
            id:toplayout
            orientation: 'horizontal'
            padding: 5
            size_hint_x: 1
            size_hint_y: 0.45
            pos_hint: {'x': 0, 'center_y': 0.5}

        HSeparator

        # Parent widget of the indicators
        BoxLayout:
            id: indicators
            orientation: 'horizontal'
            size_hint_x: 1
            size_hint_y: 0.45

        HSeparator



## kv lang Dynamic Classes.
### use them by their name (the part before the @)

<HSeparator@Widget>:
    size_hint_y: 0.005
    width: 1
    canvas:
        Color:
            rgba: .8, .8, .8, .9
        Rectangle:
            size: self.width * 0.99, 2
            pos: self.x, self.center_y
