
<ltcctrl>
    accordion_armed: accordian_armed
    accordion_unarmed: accordian_unarmed
    button_shorepower_off: button_shorepower_off
    button_shorepower_on: button_shorepower_on
    button_arm: button_arm
    button_abort: button_abort
    button_ignite: button_ignite

    AccordionItem:
        font_size: 40
        id: accordian_unarmed
        title: 'Unarmed'
        disabled: True if root.accordion_unarmed.collapse else False
        BoxLayout:
            orientation: 'vertical'
            Button:
                font_size: 40
                id: button_shorepower_on
                text: 'Enable Shore Power'
                on_release:  root.on_button_shorepower(state=True)
                disabled: True
            Button:
                font_size: 40
                id: button_shorepower_off
                text: 'Disable Shore Power'
                on_release: root.on_button_shorepower(state=False)
                disabled: True
            Button:
                font_size: 40
                id: button_arm
                text: 'Arm'
                on_release: root.arm(state=True)
                disabled: True
    AccordionItem:
        font_size: 40
        id: accordian_armed
        title: 'Armed'
        disabled: True if root.accordion_armed.collapse else False
        BoxLayout:
            orientation: 'vertical'
            Button:
                font_size: 40
                id: button_ignite
                text: 'Ignite'
                on_release: root.on_button_ignite()
            Button:
                font_size: 40
                id: button_abort
                text: 'Abort'
                on_release: root.abort()

<IgnitionPopup>
    size: root.size
    title: 'With great power comes great responsibility'
    BoxLayout:
        orientation: 'vertical'
        Label:
            font_size: 40
            text: "Are you sure you want to launch the rocket?"
        BoxLayout:
            orientation: 'horizontal'
            Button:
                font_size: 40
                text: 'Ignite'
                on_release: root.on_button_ignite(), root.dismiss()
            Label:
                text: '                          '
            Button:
                font_size: 40
                text: 'Cancel'
                on_release: root.abort(), root.dismiss()
